export interface ApiErrorBody {
  code: string;
  message: string;
}

export const ERROR_CODE = {
  VALIDATION_ERROR: 'VALIDATION_ERROR',
  MENU_UNAVAILABLE: 'MENU_UNAVAILABLE',
  IDEMPOTENCY_CONFLICT: 'IDEMPOTENCY_CONFLICT',
  ORDER_NOT_FOUND: 'ORDER_NOT_FOUND',
  ORDER_STATE_CONFLICT: 'ORDER_STATE_CONFLICT',
  ADMIN_UNAUTHORIZED: 'ADMIN_UNAUTHORIZED',
  ADMIN_LOGIN_FAILED: 'ADMIN_LOGIN_FAILED',
  SALES_PASSWORD_INVALID: 'SALES_PASSWORD_INVALID',
  UNAUTHORIZED: 'UNAUTHORIZED',
  FORBIDDEN: 'FORBIDDEN',
  NOT_FOUND: 'NOT_FOUND',
  CONFLICT: 'CONFLICT',
  TOO_MANY_REQUESTS: 'TOO_MANY_REQUESTS',
  INTERNAL_ERROR: 'INTERNAL_ERROR',
} as const;

export type ErrorCode = (typeof ERROR_CODE)[keyof typeof ERROR_CODE];

export const ERROR_CODE_HTTP_STATUS: Record<ErrorCode, number> = {
  VALIDATION_ERROR: 400,
  ADMIN_UNAUTHORIZED: 401,
  ADMIN_LOGIN_FAILED: 401,
  SALES_PASSWORD_INVALID: 403,
  ORDER_NOT_FOUND: 404,
  MENU_UNAVAILABLE: 409,
  IDEMPOTENCY_CONFLICT: 409,
  ORDER_STATE_CONFLICT: 409,
  UNAUTHORIZED: 401,
  FORBIDDEN: 403,
  NOT_FOUND: 404,
  CONFLICT: 409,
  TOO_MANY_REQUESTS: 429,
  INTERNAL_ERROR: 500,
};
